import jsPDF from "jspdf";

function generateReport(result) {

    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("CyberInbox", 20, 20);

    doc.setFontSize(12);
    doc.text("AI Email Spam Detection Report", 20, 30);

    doc.line(20, 35, 190, 35);

    doc.setFontSize(14);

    doc.text(`Prediction: ${result.prediction}`, 20, 50);

    doc.text(`Confidence: ${result.confidence}%`, 20, 65);

    doc.text(`Risk Level: ${result.risk_level}`, 20, 80);

    doc.text(`Date: ${result.timestamp}`, 20, 95);

    doc.text("Algorithm: Logistic Regression", 20, 110);

    doc.text("Vectorizer: TF-IDF", 20, 125);

    doc.text("Dataset: SpamAssassin", 20, 140);

    doc.line(20, 150, 190, 150);

    doc.setFontSize(10);

    doc.text(
        "Generated by CyberInbox",
        20,
        165
    );

    doc.save("CyberInbox_Report.pdf");

}

export default generateReport;